---
driver_plugin: vagrant
driver_config:
  customize:
    memory: 1024

platforms:
- name: ubuntu-14.04
  driver_config:
    network:
    - ["forwarded_port", {guest: 80, host: 8080}]
    - ["forwarded_port", {guest: 443, host: 8443}]
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  driver_config:
    network:
    - ["forwarded_port", {guest: 80, host: 8081}]
    - ["forwarded_port", {guest: 443, host: 8444}]
  run_list:
  - recipe[apt]
- name: centos-6.5
  driver_config:
    network:
    - ["forwarded_port", {guest: 80, host: 8082}]
    - ["forwarded_port", {guest: 443, host: 8445}]

suites:
- name: default
  run_list: ["recipe[gitlab]"]
  attributes:
    mysql:
      server_root_password: test
    gitlab:
      database:
        host: 127.0.0.1
        password: test
    authorization:
      sudo:
        groups:
        - sudo
        - wheel
- name: https
  data_bags_path: "test/integration/https/data_bags"
  encrypted_data_bag_secret_key_path: "test/integration/https/encrypted_data_bag_secret"
  run_list: ["recipe[gitlab]"]
  attributes:
    mysql:
      server_root_password: test
    gitlab:
      https: true
      certificate_databag_id: test
      database:
        host: 127.0.0.1
        password: test
